# Generated by Django 2.2.3 on 2019-09-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='missing',
        ),
    ]
