# Generated by Django 2.2.3 on 2019-09-05 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hate_users',
            field=models.ManyToManyField(related_name='hate_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
