# Generated by Django 2.2.3 on 2019-09-05 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_board_hate_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_hate_users',
            field=models.ManyToManyField(related_name='comment_hate_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_like_users',
            field=models.ManyToManyField(related_name='comment_like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
