# Generated by Django 2.2.3 on 2019-09-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190906_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='image',
            field=models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='missing_images/%Y/%m/%d/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
