# Generated by Django 2.2.3 on 2019-09-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='missing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_comments', to='board.Missing'),
        ),
        migrations.AlterField(
            model_name='missing',
            name='image',
            field=models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='missing_images/%Y/%m/%d'),
        ),
    ]
