# Generated by Django 2.2.3 on 2019-09-13 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20190906_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hate_users',
            field=models.ManyToManyField(blank=True, related_name='hate_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
