# Generated by Django 2.2.3 on 2019-09-22 23:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190922_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='missing_images/%Y/%m/%d'),
        ),
    ]
