# Generated by Django 2.2.3 on 2019-09-23 00:34

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20190923_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='missing',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='missing_images/%Y/%m/%d'),
        ),
    ]
