# Generated by Django 2.2.3 on 2019-09-10 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dename', models.TextField()),
                ('img1', models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='department')),
                ('img2', models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='department')),
                ('img3', models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='department')),
                ('map_img', models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='department')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('introduce', models.TextField()),
                ('tag', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('intro_like_users', models.ManyToManyField(related_name='intro_like_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
