# Generated by Django 2.2.3 on 2019-09-13 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_intro_de_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='intro_like_users',
            field=models.ManyToManyField(default=0, related_name='intro_like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
