# Generated by Django 2.2.3 on 2019-09-13 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_auto_20190913_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='intro_like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='intro_like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
