# Generated by Django 2.2.3 on 2019-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_auto_20190913_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
