# Generated by Django 2.2.3 on 2019-09-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_intro_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='menufan',
            field=models.FileField(default='https://image.flaticon.com/icons/svg/149/149852.svg', upload_to='department'),
        ),
    ]
