# Generated by Django 2.2.1 on 2019-09-20 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0008_intro_menufan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
